# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformTaskV2@2 
  inputs:
     provider: 'azurerm'
     command: 'init'
     workingDirectory: $(System.DefaultWorkingDirectory)
     backendServiceArm: 'SERVICE CONNECTION NAME'
     backendAzureRmResourceGroupName: 'RESOURCE GROUP NAME'
     backendAzureRmStorageAccountName: 'STORAGE ACCOUNT NAME'
     backendAzureRmContainerName: 'CONTAINER NAME'
     backendAzureRmKey: 'tf/terraform.tfstate'

- task: TerraformTaskV2@2 
  inputs:
     provider: 'azurerm'
     command: 'apply'
     workingDirectory: $(System.DefaultWorkingDirectory)
     environmentServiceNameAzureRM: 'SERVICE CONNECTION NAME'
